### Numpy:

* Numpy stands for numerical python. The primary use of numpy is effiecient data handling and manipulation.

* Numpy has inbuilt function for working with numpy object.
  
* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object (ndarray) that is up to 50x faster than traditional Python lists.


In [ ]:
!pip install numpy

In [3]:
import numpy as np
import os

In [41]:
os.getcwd()

'C:\\Users\\User'

In [42]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\User\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\user\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

### Numpy Arrays:

In [5]:
arr = np.array()
arr

TypeError: array() missing required argument 'object' (pos 0)

In [7]:
arr = np.array([])

In [9]:
arr

array([], dtype=float64)

In [462]:
type(arr)

numpy.ndarray

In [464]:
len(arr)

0

In [17]:
arr = np.array(object = [1,2,3,4])

In [15]:
arr

array([1, 2, 3, 6])

In [468]:
arr.dtype

dtype('float64')

In [21]:
arr = np.array(['Apple','Orange','Banana','Watermelon','Jackfruit'])

In [23]:
arr

array(['Apple', 'Orange', 'Banana', 'Watermelon', 'Jackfruit'],
      dtype='<U10')

In [ ]:

#Array is the collection of similar data type.

In [512]:
lst

#type(lst)

[1, 2, 3, 6]

In [480]:
lst.index(6)

3

In [472]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [25]:
arr = np.array([1, 2.5, 3])  # Mixed int and float
arr.dtype

dtype('float64')

In [532]:
arr = np.array([1,4,6,7,'ABC'])

arr.dtype

dtype('<U11')

In [434]:
tp = (0,5,7,9,0,4)

In [436]:
np.array(tp)


array([0, 5, 7, 9, 0, 4])

In [438]:
setA = {1.5,6,8,-8.5}

In [440]:
np.array(setA)

array({8, 1.5, 6, -8.5}, dtype=object)

### Multidimensional arrays:

In [444]:
np.array([2,3,4,5,-10])

array([  2,   3,   4,   5, -10])

In [446]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [46]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr_3d = np.array([[[1,5],[3,4],[5,6],[7,9],[8,9]],[[1,5],[3,4],[5,6],[7,9],[8,9]]])

In [29]:
arr_3d

array([[[1, 5],
        [3, 4],
        [5, 6],
        [7, 9],
        [8, 9]],

       [[1, 5],
        [3, 4],
        [5, 6],
        [7, 9],
        [8, 9]]])

In [49]:
arr

array([ 1.  ,  5.  ,  7.  ,  8.  , 10.25])

In [452]:
arr.ndim

1

In [52]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr_2d.ndim

2

In [54]:
arr_3d.ndim

3

In [56]:
arr.shape

(5,)

In [57]:
arr_2d.shape

(2, 3)

In [31]:
arr_3d.shape

(2, 5, 2)

In [454]:
arr_2d.size

6

In [888]:
# flatten()
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])




flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6 7 8 9]


In [64]:
arr = np.array([22,-36,32,47,71,-45])

In [65]:
arr

array([ 22, -36,  32,  47,  71, -45])

In [66]:
# INDEXING AND SLICING
arr[1]

-36

In [67]:
arr[1:4]

array([-36,  32,  47])

In [70]:
arr[2:]

array([ 32,  47,  71, -45])

In [71]:
arr[:3]

array([ 22, -36,  32])

In [72]:
arr[::-1]

array([-45,  71,  47,  32, -36,  22])

In [73]:
arr

array([ 22, -36,  32,  47,  71, -45])

In [74]:
arr[1:-1]

array([-36,  32,  47,  71])

In [35]:
# 2D ARRAY - INDEXING AND SLICING
arr = np.array([['Python','R','C++'], [len('Python'),len('R'), 
                                       len('C++')]])

In [37]:
arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [43]:
arr[1][2]

'3'

In [45]:
arr[0:2][0:1]

array([['Python', 'R', 'C++']], dtype='<U11')

In [49]:
arr[0].shape

(3,)

In [89]:
arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [92]:
arr[0:]

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [94]:
arr[0,[0,1]]

array(['Python', 'R'], dtype='<U11')

In [538]:
arr = np.array([[1,2,3],[4,5,6]])

In [51]:
arr

array([['Python', 'R', 'C++'],
       ['6', '1', '3']], dtype='<U11')

In [111]:
arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [112]:
# False : 0
# True : 1

In [540]:
(arr > 2) & (arr < 5)

array([[False, False,  True],
       [ True, False, False]])

In [542]:
arr[(arr > 2) |(arr < 5)]

array([1, 2, 3, 4, 5, 6])

In [57]:
arr_numbers = np.array([34,56,87,90,34,56,12,34,67,89,90,88,
                      35,67,12,45,78,23,56])

In [556]:
lst = [34,56,87,90,34,56,12,34,67,89,90,88,35,67,12,45,78,23,56]

In [558]:
list(filter(lambda x : x > 50, lst))

[56, 87, 90, 56, 67, 89, 90, 88, 67, 78, 56]

In [59]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [63]:
arr_numbers[arr_numbers > 50]

array([56, 87, 90, 56, 67, 89, 90, 88, 67, 78, 56])

In [67]:
len(arr_numbers[arr_numbers > 50])

11

In [568]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [570]:
arr_numbers[arr_numbers % 2 == 0]

array([34, 56, 90, 34, 56, 12, 34, 90, 88, 12, 78, 56])

In [572]:
arr_numbers[arr_numbers % 2 != 0]

array([87, 67, 89, 35, 67, 45, 23])

In [574]:
arr_numbers[arr_numbers % 5 == 0]

array([90, 90, 35, 45])

### numpy where method

In [69]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

In [71]:
np.where(arr_numbers < 50)

(array([ 0,  4,  6,  7, 12, 14, 15, 17], dtype=int64),)

In [582]:
np.where(arr_numbers == 90)

(array([ 3, 10], dtype=int64),)

In [584]:
np.where((arr_numbers >50) & (arr_numbers < 60))

(array([ 1,  5, 18], dtype=int64),)

In [586]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [588]:
np.where(arr_2d > 3)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

In [590]:
arr_2d > 3

array([[False, False, False],
       [ True,  True,  True]])

In [592]:
arr_2d[np.where(arr_2d > 3)]

array([4, 5, 6])

In [594]:
arr_numbers

array([34, 56, 87, 90, 34, 56, 12, 34, 67, 89, 90, 88, 35, 67, 12, 45, 78,
       23, 56])

### Operations on Numpy Arrays:

In [75]:
np_arr = np.array([1,2,3])

In [600]:
np_arr

array([1, 2, 3])

### Adding elements 

In [77]:
np.append(arr = np_arr, values = 4)

array([1, 2, 3, 4])

In [628]:
np.append(np_arr,4)

array([1, 2, 3, 4])

In [79]:
np.append(np_arr,[5,6,7,8,9])

array([1, 2, 3, 5, 6, 7, 8, 9])

### numpy delete method

This method can delete an item based on item's index.

In [81]:
np.delete(np_arr, 2)

array([1, 2])

### How to generate random numbers

In [91]:
np.random.randint(low = 10, high = 99, size = 50)

array([16, 55, 20, 53, 30, 58, 69, 56, 10, 60, 96, 19, 25, 23, 78, 86, 49,
       10, 12, 14, 89, 51, 49, 20, 30, 61, 87, 43, 80, 18, 90, 51, 10, 50,
       41, 76, 51, 47, 91, 32, 30, 24, 36, 71, 53, 46, 40, 60, 36, 94])

In [97]:
np.random.randint(low = 10, high = 99, size = (5,10))

array([[79, 61, 46, 53, 72, 53, 73, 18, 91, 85],
       [60, 13, 78, 84, 88, 82, 72, 36, 50, 87],
       [37, 89, 54, 72, 28, 25, 13, 53, 68, 74],
       [55, 20, 67, 30, 19, 54, 83, 65, 97, 11],
       [22, 66, 84, 44, 34, 42, 29, 73, 39, 78]])

In [103]:
np.random.rand(20)

array([0.03709034, 0.440806  , 0.82498917, 0.86375982, 0.50107311,
       0.43519007, 0.3401378 , 0.87713747, 0.57303135, 0.44142825,
       0.30819417, 0.96894429, 0.91671104, 0.43037857, 0.10376167,
       0.99314068, 0.60187578, 0.60013966, 0.42279412, 0.46453575])

In [109]:
np.random.randn(20) #normal distribution with a mean of 0 and standard deviation of 1.


array([ 0.427794  , -1.84504258,  0.85236345,  1.28573366,  0.09196824,
       -1.9275731 , -0.46231864,  1.50461543, -0.82346977,  0.21581116,
        1.60635931, -0.14091052, -0.2363037 ,  0.57673807, -2.36396292,
        0.44030663, -0.44962689,  0.34160554,  1.19432522,  0.34772594])

In [117]:
arr = np.array([1, 2, 3, 4, 5])
random_num=np.random.choice(arr)
print(random_num)

2


In [135]:
#exercise reference
x1=np.random.randint(low = 1, high = 11, size = (3,3))
x1




array([[ 5,  5, 10],
       [ 4,  3, 10],
       [ 7,  2,  3]])

In [137]:
x2= np.array([1, 2, 3])

result = x1 + x2
result

array([[ 6,  7, 13],
       [ 5,  5, 13],
       [ 8,  4,  6]])

### Numpy Seed

Whenever you are working on numbers and you are performing any analysis on your dataset and the same data you want in your system.

In [155]:
np.random.seed(10)
np.random.randint(low = 10, high = 99, size = 50)

array([19, 25, 74, 38, 39, 18, 83, 10, 50, 46, 26, 21, 64, 98, 72, 43, 82,
       88, 59, 61, 64, 87, 79, 23, 35, 23, 96, 40, 40, 22, 75, 41, 67, 46,
       37, 28, 87, 32, 33, 21, 38, 84, 98, 19, 25, 28, 90, 81, 98, 21])

In [163]:
np.random.seed(11)
np.random.randint(low = 10, high = 99, size = 50)

array([35, 73, 90, 91, 65, 23, 86, 43, 81, 92, 34, 58, 42, 55, 14, 44, 22,
       11, 84, 47, 94, 91, 34, 27, 77, 80, 53, 74, 89, 33, 37, 80, 20, 67,
       37, 54, 24, 17, 65, 89, 74, 50, 37, 15, 63, 81, 60, 69, 11, 13])

In [173]:
np.random.seed(42)
np.random.randint(low = 10, high = 99, size = 50)

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97, 33, 12, 31, 62, 11, 97, 39,
       47, 11, 73, 69, 30, 42, 85, 67, 31, 98, 58, 68, 51, 69, 89, 24, 71,
       71, 56, 71, 60, 64, 73, 12, 60, 16, 30, 82, 48, 27, 13, 98, 69])

In [177]:
np.random.seed(100)
np.random.randint(low = 10, high = 99, size = 50)

array([18, 34, 77, 97, 89, 58, 20, 62, 63, 76, 24, 44, 34, 25, 70, 68, 26,
       19, 96, 12, 37, 14, 41, 11, 23, 93, 14, 69, 77, 17, 59, 57, 75, 71,
       24, 65, 81, 90, 12, 29, 73, 63, 37, 66, 40, 58, 57, 49, 48, 54])

In [181]:
np.random.seed(10000)
np.random.randint(low = 10, high = 99, size = 50)

array([22, 63, 41, 50, 57, 12, 31, 82, 71, 27, 80, 82, 95, 64, 49, 44, 72,
       85, 61, 86, 24, 25, 17, 82, 53, 51, 84, 44, 36, 54, 45, 87, 40, 16,
       87, 68, 56, 98, 14, 88, 89, 92, 95, 90, 70, 65, 50, 96, 78, 37])

In [674]:
np.random.seed(10)
np.random.randint(10,1000,5)

array([275, 135, 537, 330, 379])

### Concatenating and Splitting arrays:

In [676]:
arr1 = np.array([[1,2],[-4,3],[2,-5]])

In [678]:
arr1

array([[ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [680]:
arr2 = np.array([[1,2],[-4,3],[2,-5]])
arr2

array([[ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [682]:
np.concatenate((arr1,arr2))

array([[ 1,  2],
       [-4,  3],
       [ 2, -5],
       [ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [684]:
np.concatenate((arr1,arr2), axis = 0)

array([[ 1,  2],
       [-4,  3],
       [ 2, -5],
       [ 1,  2],
       [-4,  3],
       [ 2, -5]])

In [686]:
np.concatenate((arr1,arr2), axis = 1)

array([[ 1,  2,  1,  2],
       [-4,  3, -4,  3],
       [ 2, -5,  2, -5]])

In [688]:
arr3 = np.concatenate((arr1,arr2), axis = 1)
arr3

array([[ 1,  2,  1,  2],
       [-4,  3, -4,  3],
       [ 2, -5,  2, -5]])

In [690]:
np.split(ary = arr3, indices_or_sections=[1])

[array([[1, 2, 1, 2]]),
 array([[-4,  3, -4,  3],
        [ 2, -5,  2, -5]])]

In [804]:
np.split(ary = arr3, indices_or_sections=[2])

[array([[ 1,  2,  1,  2],
        [-4,  3, -4,  3]]),
 array([[ 2, -5,  2, -5]])]

### Arithematic Operations:

In [692]:
revenue_nov = np.array([3485.09, 2784.89, 1930.80])
revenue_dec = np.array([4859.90,1800.00,4500.50])

In [694]:
revenue_nov + revenue_dec

array([8344.99, 4584.89, 6431.3 ])

In [696]:
total_revenue = revenue_nov + revenue_dec # element wise addition

In [698]:
total_revenue

array([8344.99, 4584.89, 6431.3 ])

In [700]:
revenue_nov + 50 # BROADCASTING

array([3535.09, 2834.89, 1980.8 ])

In [702]:
revenue_nov - 50

array([3435.09, 2734.89, 1880.8 ])

In [704]:
revenue_nov / 2

array([1742.545, 1392.445,  965.4  ])

In [706]:
revenue_nov * 2

array([6970.18, 5569.78, 3861.6 ])

In [708]:
v1 = np.array([[5,-4],[-3,2]])
v2 = np.array([[3,8],[-6,0]])

In [810]:
v1

array([[ 5, -4],
       [-3,  2]])

In [712]:
v2

array([[ 3,  8],
       [-6,  0]])

In [912]:
v1+v2  # element-wise

array([[ 8,  4],
       [-9,  2]])

In [914]:
v1 -v2

array([[  2, -12],
       [  3,   2]])

### Mathematical and Statistical Function in numpy

In [936]:
x1 = np.array([1,2,3])
x2 = np.array([2,2,2])

In [726]:
np.add(x1,x2)

array([3, 4, 5])

In [728]:
np.subtract(x1,x2)

array([-1,  0,  1])

In [730]:
np.multiply(x1,x2)

array([2, 4, 6])

In [938]:
np.divide(x1,x2)

array([0.5, 1. , 1.5])

In [940]:
np.dot(x1,x2)

12

In [732]:
np.power(x1,2)

array([1, 4, 9], dtype=int32)

In [734]:
np.sqrt(x2)

array([1.41421356, 1.41421356, 1.41421356])

In [740]:
np.divmod(x1,x2)

(array([0, 1, 1]), array([1, 0, 1]))

In [742]:
quotient, remainder = np.divmod(x1,x2)

In [744]:
quotient

array([0, 1, 1])

In [746]:
remainder

array([1, 0, 1])

In [748]:
np.divide(x1,x2)

array([0.5, 1. , 1.5])

In [750]:
np.floor_divide(x1,x2)

array([0, 1, 1])

In [752]:
np.mod(x1,x2)

array([1, 0, 1])

In [856]:
np.mean(x1)
np.average(x1)

2.0

In [848]:
np.sum(x1)

6

In [850]:
np.min(x1)

1

In [852]:
np.max(x1)

3

In [121]:
np.std(arr)

1.707825127659933

In [122]:
np.median(arr)

3.5

In [766]:
arr1 = np.array([4,np.nan,5,6,np.nan,5,10,np.nan])

In [768]:
arr1

array([ 4., nan,  5.,  6., nan,  5., 10., nan])

In [770]:
sum(arr1)

nan

In [774]:
np.mean(arr1)

nan

In [788]:
np.max(arr1)


nan

In [776]:
np.std(arr1)

nan

In [780]:
np.nansum(arr)

15

In [782]:
np.nanmean(arr)

3.0

In [786]:
np.nanmax(arr)

5

In [878]:
# finding min , max in 2d 

array_2d = np.array([[12, 7, 9, 15],
                     [8, 18, 10, 6],
                     [14, 3, 11, 19],
                     [5, 20, 13, 4]])



min_per_row = np.min(array_2d, axis=1)
print( min_per_row)



[7 6 3 4]


In [880]:

max_per_row = np.max(array_2d, axis=1)
print(max_per_row)




[15 18 19 20]


In [872]:
min_per_column = np.min(array_2d, axis=0)
print(min_per_column)




[5 3 9 4]


In [874]:
max_per_column = np.max(array_2d, axis=0)
print(max_per_column)


[14 20 13 19]


In [ ]:
# print(dir(__builtins__))

In [838]:
#  np.array(), np.arange(), np.zeros(), np.ones(),, np.linspace()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [790]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [792]:
np.arange(60).reshape(2,6,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [812]:
arr = np.arange(30).reshape(6,5)

In [796]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [814]:
arr.sum()

435

In [816]:
arr.sum(axis=0)

array([75, 81, 87, 93, 99])

In [818]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

In [133]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [820]:
arr[0][0] = 1

In [822]:
arr

array([[ 1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [832]:
np.mean(arr)
#arr.mean()

14.533333333333333

In [826]:
arr.mean(axis=0)

array([12.66666667, 13.5       , 14.5       , 15.5       , 16.5       ])

In [828]:
arr.mean(axis=1)

array([ 2.2,  7. , 12. , 17. , 22. , 27. ])

In [900]:
# zeros()

arr = np.ones(5)
print(arr)


[1. 1. 1. 1. 1.]


In [904]:
arr = np.ones((3, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [908]:
arr = np.zeros((3))

print(arr)

[0. 0. 0.]


In [906]:
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [896]:
# linspace

arr = np.linspace(0, 10, num=5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [898]:
arr = np.linspace(-5, 5, num=7)
arr

array([-5.        , -3.33333333, -1.66666667,  0.        ,  1.66666667,
        3.33333333,  5.        ])

In [942]:
# Sorting

arr = np.array([34, 12, 7, 89, 45, 19])

# Sorting in ascending order
ascending_arr = np.sort(arr)
print(ascending_arr)

# Sorting in descending order
descending_arr = np.sort(arr)[::-1]
print( descending_arr)

[ 7 12 19 34 45 89]
[89 45 34 19 12  7]


In [836]:
print("All the function from numpy: ",
     [i for i in dir(np) if "__" not in i])

All the function from numpy:  ['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_typing', '_using_numpy2_behavior', '_utils', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'all', 'allclose', 'all

In [ ]:
# print("All the methods form list: ", [i for i in dir(list) if "__" not in i])
# print()
# print("All the methods form tuple: ", [i for i in dir(tuple) if "__" not in i])
# print()
# print("All the methods form set: ", [i for i in dir(set) if "__" not in i])

# print()
# print("All the methods form dict: ", [i for i in dir(dict) if "__" not in i])
# print()
# print("All the methods form str: ", [i for i in dir(str) if "__" not in i])